#!/usr/bin/env bash
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-2.95.3/gcc_2.html -O 2.95.3.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-3.0.3/gcc/Warning-Options.html -O 3.0.3.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-3.1.1/gcc/Warning-Options.html -O 3.1.1.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-3.2.1/gcc/Warning-Options.html -O 3.2.1.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-3.3.1/gcc/Warning-Options.html -O 3.3.1.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-3.4.0/gcc/Warning-Options.html -O 3.4.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-4.0.0/gcc/Warning-Options.html -O 4.0.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-4.1.0/gcc/Warning-Options.html -O 4.1.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-4.2.0/gcc/Warning-Options.html -O 4.2.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-4.3.0/gcc/Warning-Options.html -O 4.3.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-4.4.0/gcc/Warning-Options.html -O 4.4.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-4.5.0/gcc/Warning-Options.html -O 4.5.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-4.6.0/gcc/Warning-Options.html -O 4.6.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-4.7.0/gcc/Warning-Options.html -O 4.7.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-4.8.0/gcc/Warning-Options.html -O 4.8.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-4.9.0/gcc/Warning-Options.html -O 4.9.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-5.1.0/gcc/Warning-Options.html -O 5.1.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/Warning-Options.html -O 5.2.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-5.3.0/gcc/Warning-Options.html -O 5.3.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-5.4.0/gcc/Warning-Options.html -O 5.4.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-5.5.0/gcc/Warning-Options.html -O 5.5.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-6.1.0/gcc/Warning-Options.html -O 6.1.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-6.2.0/gcc/Warning-Options.html -O 6.2.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-6.3.0/gcc/Warning-Options.html -O 6.3.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-6.4.0/gcc/Warning-Options.html -O 6.4.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-6.5.0/gcc/Warning-Options.html -O 6.5.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-7.1.0/gcc/Warning-Options.html -O 7.1.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Warning-Options.html -O 7.2.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-7.3.0/gcc/Warning-Options.html -O 7.3.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-7.4.0/gcc/Warning-Options.html -O 7.4.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-7.5.0/gcc/Warning-Options.html -O 7.5.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gcc/Warning-Options.html -O 8.1.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Warning-Options.html -O 8.2.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/Warning-Options.html -O 8.3.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-8.4.0/gcc/Warning-Options.html -O 8.4.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-8.5.0/gcc/Warning-Options.html -O 8.5.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Warning-Options.html -O 9.1.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gcc/Warning-Options.html -O 9.2.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-9.3.0/gcc/Warning-Options.html -O 9.3.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-9.4.0/gcc/Warning-Options.html -O 9.4.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-9.5.0/gcc/Warning-Options.html -O 9.5.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Warning-Options.html -O 10.1.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-10.2.0/gcc/Warning-Options.html -O 10.2.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-10.3.0/gcc/Warning-Options.html -O 10.3.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-10.4.0/gcc/Warning-Options.html -O 10.4.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-11.1.0/gcc/Warning-Options.html -O 11.1.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-11.2.0/gcc/Warning-Options.html -O 11.2.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-11.3.0/gcc/Warning-Options.html -O 11.3.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-12.1.0/gcc/Warning-Options.html -O 12.1.0.html
wget -c -nv https://gcc.gnu.org/onlinedocs/gcc-12.2.0/gcc/Warning-Options.html -O 12.2.0.html
